### ISSUE TITLE
BMCSimulator requests are failing with Configured IP address and port

### ISSUE THREAD

**Issue by rohitkumar-ro** [ODIM-Project/BMCSimulator#1]
After installing BMCSimuator, getting 503(Not found) error instead of 200 (OK) while performing GET/curl operation with the VM ipv4 ip.

URL:http://<VM_ipv4-IP>:1234/redfish/v1

Response:-

It is working as expected when IP address and port is passed in the command line but does not work when same is configured in "simulator-config.json" file.
 

cat simulator-config.json
{
"binding":

{ "ip": "VM_IP", "port": "1234", "odimUrl": "" }

,
"security": {
"server":

{ "useTLS": false, "basicCredentials": "admin:admin", "externalKeyStoreLocation": "", "externalKeyStorePassword": "", "useServerMTLS": "false" }

,
"trustStore":

{ "externalTrustStoreLocation": "", "externalTrustStorePassword": "" }

,
"httpClient":

{ "withBasic": true, "basicCredentials": "admin:admin", "useTLS": false, "serverCertificateVerificationEnabled": true }

},
"cache":

{ "etags": false }

,
"resourcesConfig": {}
}

 

Cmd:- java -jar simulator-runner-1.0-SNAPSHOT.jar run BMC -c simulator-config.json

Output:-

22:33:25.116 [main] INFO c.o.s.commandline.RunSimulatorsCmd - Running simulator with name: 'BMC' on port null
22:33:27.201 [main] DEBUG com.odim.utils.Timing - Simulator init time: 1219 ms
22:33:27.296 [main] DEBUG c.o.simulator.ResourcesConfigurator - Configuring resources
22:33:27.296 [main] DEBUG c.o.simulator.ResourcesConfigurator - Configuring resources time: 1 ms
22:33:27.297 [main] INFO io.javalin.Javalin - Starting Javalin ...
22:33:27.407 [main] INFO io.javalin.Javalin - Listening on http://127.0.0.1:42075/
22:33:27.407 [main] INFO io.javalin.Javalin - Javalin started in 111ms \o/
22:33:27.407 [main] INFO com.odim.simulator.http.Deployment - BMCSimulator started at: http://127.0.0.1:42075/redfish/v1

**Comment by ArturBaryla** [comment]
Hi. I see in logs the file is not loaded. How did you start simulator? Did you used "-c simulation-config.json"? Maybe try it

**Comment by ArturBaryla** [comment]
I see config has been not loaded. 
Is your VM_IP is a really IP adress or are you trying to use env?

**Comment by dlemiech** [comment]
Hi rohitkumar-ro!

Additionally to Artur check could you please ensure the directory you are using command: 
`java -jar simulator-runner-1.0-SNAPSHOT.jar run BMC -c simulator-config.json`

Looks like the config does not match the run. The log says: `BMCSimulator started at: http://127.0.0.1:42075/redfish/v1` which means simulator started on port 42075.

Are you able to curl `http://127.0.0.1:42075/redfish/v1`?

**Comment by rohitkumar-ro** [comment]
I am using talend app in chrome browser to add BMCSimulator as a server in the ODIM using post action but I am getting below SSL error while vaidating the certificate

ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by rohitkumar-ro** [comment]
After giving the absolute path for the simulator-config.json file BMCSimulator started.

we can close this issue
